[package]
name = "passrat"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
chrono = { version = "0.4.45", features = ["serde"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
email-address-parser = "2.0.2"
ratatui = "0.30.2"
rusqlite = { version = "0.39.0", features = ["bundled-sqlcipher"] }
rustpass = { version = "0.2.1", features = [] }
serde = { version = "1.0.229", features = ["derive"] }
url = "2.5.8"
xdg = "3.0.0"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
# DENY PANICS:
unwrap_used = "deny"
# expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny" 
unreachable = "deny" 
unimplemented = "deny" 
unchecked_time_subtraction = "deny" 
todo = "deny" 
string_slice = "deny" 
panic_in_result_fn = "deny" 
panic = "deny"
exit = "deny"
as_conversions = "deny"
